const cars = [
  {
    make: "Toyota",
    model: "Camry",
    imageSrc: "Toyota Camry",
    year: 2022,
    color: "Silver",
    price: 50,
    availability: true,
  },
  {
    make: "Nissan",
    model: "Altima",
    imageSrc: "",
    year: 2022,
    color: "Black",
    price: 30,
    availability: false,
  },
  {
    make: "Honda",
    model: "Civic",
    imageSrc: "",
    year: 2021,
    color: "Red",
    price: 45,
    availability: true,
  },
  {
    make: "Kia",
    model: "Rio",
    imageSrc: "",
    year: 2022,
    color: "Pearl-White",
    price: 60,
    availability: false,
  },
  {
    make: "Ford",
    model: "F-150",
    imageSrc: "",
    year: 2023,
    color: "Blue",
    price: 75,
    availability: true,
  },
  {
    make: "Toyota",
    model: "Tundra",
    imageSrc: "",
    year: 2023,
    color: "White",
    price: 85,
    availability: false,
  },
  {
    make: "Toyota",
    model: "Rav4 Plug-In Hybrid",
    imageSrc: "",
    year: 2023,
    color: "White",
    price: 75,
    availability: true,
  },
  {
    make: "Chevrolet",
    model: "Tahoe",
    imageSrc: "",
    year: 2021,
    color: "Maroon",
    price: 85,
    availability: false,
  },
  {
    make: "Tesla",
    model: "Model Y long range",
    imageSrc: "",
    year: 2020,
    color: "Black",
    price: 75,
    availability: true,
  },
  {
    make: "Hyundai",
    model: "Ioniq 5 SE",
    imageSrc: "",
    year: 2023,
    color: "Silver",
    price: 50,
    availability: false,
  },
  {
    make: "Chrysler Pacifica Plug-In Hybrid",
    model: "Pinnacle",
    imageSrc: "",
    year: 2023,
    color: "Silver",
    price: 80,
    availability: false,
  },
  {
    make: "Volkswagen",
    model: "Eurovan MV",
    imageSrc: "",
    year: 2003,
    color: "Blue",
    price: 45,
    availability: true,
  },
  {
    make: "Mercedes-Benz",
    model: "SL 63 AMG 4Matic",
    imageSrc: "",
    year: 2022,
    color: "Metallic Grey",
    price: 85,
    availability: false,
  },
  {
    make: "Volkswagen Beetle",
    model: "2.0T FWD",
    imageSrc: "",
    year: 2019,
    color: "Yellow",
    price: 60,
    availability: true,
  },
  {
    make: "Porsche 911",
    model: "GT3 RS",
    imageSrc: "",
    year: 2016,
    color: "Burgundy",
    price: 85,
    availability: false,
  },
  {
    make: "BMW M4",
    model: "GTS Coupe",
    imageSrc: "",
    year: 2018,
    color: "Lime-Green",
    price: 70,
    availability: false,
  },
];
